<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\City;
use App\Models\Event;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class EventSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $events = [
            [
                'category' => 'Technology',
                'city' => 'Karachi',
                'name' => 'Pakistan Tech Summit 2026',
                'description' => 'A technology conference bringing together developers, startups, technology leaders, and digital innovators.',
                'location_name' => 'Expo Centre Karachi',
                'address' => 'University Road, Gulshan-e-Iqbal, Karachi',
                'primary_image' => 'events/default_primary.jpg',
                'cover_image' => 'events/default_cover.jpg',
                'type' => 'paid',
                'price' => 5000,
                'start_at' => '2026-09-12 10:00:00',
                'end_at' => '2026-09-12 17:00:00',
                'max_attendees' => 500,
            ],

            [
                'category' => 'Workshops',
                'city' => 'Lahore',
                'name' => 'Modern Laravel Development Workshop',
                'description' => 'A practical workshop covering Laravel application architecture, Eloquent relationships, testing, and deployment.',
                'location_name' => 'Arfa Software Technology Park',
                'address' => 'Ferozepur Road, Lahore',
                'primary_image' => 'events/default_primary.jpg',
                'cover_image' => 'events/default_cover.jpg',
                'type' => 'free',
                'price' => 0,
                'start_at' => '2026-09-19 10:00:00',
                'end_at' => '2026-09-19 16:00:00',
                'max_attendees' => 80,
            ],

            [
                'category' => 'Concerts & Music',
                'city' => 'Islamabad',
                'name' => 'Capital Music Night',
                'description' => 'An evening of live music featuring emerging Pakistani artists and local bands.',
                'location_name' => 'Jinnah Convention Centre',
                'address' => 'Constitution Avenue, Islamabad',
                'primary_image' => 'events/default_primary.jpg',
                'cover_image' => 'events/default_cover.jpg',
                'type' => 'piad',
                'price' => 2500,
                'start_at' => '2026-09-25 19:00:00',
                'end_at' => '2026-09-25 23:00:00',
                'max_attendees' => 1000,
            ],

            [
                'category' => 'Networking',
                'city' => 'Karachi',
                'name' => 'Karachi Startup Networking Evening',
                'description' => 'A networking event for startup founders, entrepreneurs, investors, and technology professionals.',
                'location_name' => 'NIC Karachi',
                'address' => 'University Road, Karachi',
                'primary_image' => 'events/default_primary.jpg',
                'cover_image' => 'events/default_cover.jpg',
                'type' => 'free',
                'price' => 0,
                'start_at' => '2026-09-28 18:00:00',
                'end_at' => '2026-09-28 21:00:00',
                'max_attendees' => 150,
            ],

            [
                'category' => 'Education',
                'city' => 'Lahore',
                'name' => 'Future of Digital Education',
                'description' => 'An educational seminar discussing technology, online learning, and the future of digital education in Pakistan.',
                'location_name' => 'Lahore University Hall',
                'address' => 'Canal Bank Road, Lahore',
                'primary_image' => 'events/default_primary.jpg',
                'cover_image' => 'events/default_cover.jpg',
                'type' => 'paid',
                'price' => 1000,
                'start_at' => '2026-10-03 11:00:00',
                'end_at' => '2026-10-03 15:00:00',
                'max_attendees' => 300,
            ],

            [
                'category' => 'Sports',
                'city' => 'Rawalpindi',
                'name' => 'Twin Cities Cricket Tournament',
                'description' => 'A weekend cricket tournament featuring amateur teams from Rawalpindi and Islamabad.',
                'location_name' => 'Rawalpindi Cricket Stadium',
                'address' => 'Murree Road, Rawalpindi',
                'primary_image' => 'events/default_primary.jpg',
                'cover_image' => 'events/default_cover.jpg',
                'type' => 'paid',
                'price' => 1000,
                'start_at' => '2026-10-10 09:00:00',
                'end_at' => '2026-10-11 18:00:00',
                'max_attendees' => 500,
            ],

            [
                'category' => 'Arts & Culture',
                'city' => 'Lahore',
                'name' => 'Lahore Arts & Culture Exhibition',
                'description' => 'An exhibition showcasing contemporary Pakistani art, photography, and traditional artwork.',
                'location_name' => 'Alhamra Arts Centre',
                'address' => 'The Mall, Lahore',
                'primary_image' => 'events/default_primary.jpg',
                'cover_image' => 'events/default_cover.jpg',
                'type' => 'paid',
                'price' => 500,
                'start_at' => '2026-10-15 11:00:00',
                'end_at' => '2026-10-18 20:00:00',
                'max_attendees' => 400,
            ],

            [
                'category' => 'Food & Drink',
                'city' => 'Karachi',
                'name' => 'Karachi Street Food Festival',
                'description' => 'A food festival featuring popular street food vendors, local chefs, desserts, and live entertainment.',
                'location_name' => 'Beach View Park',
                'address' => 'Sea View Road, Clifton, Karachi',
                'primary_image' => 'events/default_primary.jpg',
                'cover_image' => 'events/default_cover.jpg',
                'type' => 'paid',
                'price' => 800,
                'start_at' => '2026-10-23 16:00:00',
                'end_at' => '2026-10-25 23:00:00',
                'max_attendees' => 2000,
            ],

            [
                'category' => 'Health & Wellness',
                'city' => 'Islamabad',
                'name' => 'Islamabad Wellness & Fitness Day',
                'description' => 'A community wellness event featuring fitness sessions, nutrition talks, yoga, and health awareness activities.',
                'location_name' => 'F-9 Park',
                'address' => 'F-9 Park, Islamabad',
                'primary_image' => 'events/default_primary.jpg',
                'cover_image' => 'events/default_cover.jpg',
                'type' => 'free',
                'price' => 0,
                'start_at' => '2026-11-01 08:00:00',
                'end_at' => '2026-11-01 14:00:00',
                'max_attendees' => 600,
            ],

            [
                'category' => 'Technology',
                'city' => 'Islamabad',
                'name' => 'Pakistan AI & Machine Learning Conference',
                'description' => 'A conference exploring artificial intelligence, machine learning, automation, and emerging technologies.',
                'location_name' => 'Serena Hotel Islamabad',
                'address' => 'Khayaban-e-Suharwardy, Islamabad',
                'primary_image' => 'events/default_primary.jpg',
                'cover_image' => 'events/default_cover.jpg',
                'type' => 'free',
                'price' => 0,
                'start_at' => '2026-11-07 09:00:00',
                'end_at' => '2026-11-07 18:00:00',
                'max_attendees' => 450,
            ],

            [
                'category' => 'Career & Jobs',
                'city' => 'Lahore',
                'name' => 'Lahore Career & Job Fair 2026',
                'description' => 'A career fair connecting students, professionals, employers, and recruiters from multiple industries.',
                'location_name' => 'Expo Centre Lahore',
                'address' => 'Johar Town, Lahore',
                'primary_image' => 'events/default_primary.jpg',
                'cover_image' => 'events/default_cover.jpg',
                'type' => 'free',
                'price' => 0,
                'start_at' => '2026-11-14 10:00:00',
                'end_at' => '2026-11-14 17:00:00',
                'max_attendees' => 1200,
            ],

            [
                'category' => 'Meetups',
                'city' => 'Karachi',
                'name' => 'PHP & Laravel Developers Meetup',
                'description' => 'A casual meetup for PHP and Laravel developers to share knowledge, discuss projects, and connect with the local developer community.',
                'location_name' => 'The Hive',
                'address' => 'Shahrah-e-Faisal, Karachi',
                'primary_image' => 'events/default_primary.jpg',
                'cover_image' => 'events/default_cover.jpg',
                'type' => 'Meetup',
                'price' => 0,
                'start_at' => '2026-11-20 18:30:00',
                'end_at' => '2026-11-20 21:00:00',
                'max_attendees' => 100,
            ],

            [
                'category' => 'Business',
                'city' => 'Islamabad',
                'name' => 'Pakistan Business Leadership Forum',
                'description' => 'A business forum focused on leadership, entrepreneurship, economic trends, and business growth strategies.',
                'location_name' => 'Islamabad Marriott Hotel',
                'address' => 'Aga Khan Road, F-5/1, Islamabad',
                'primary_image' => 'events/default_primary.jpg',
                'cover_image' => 'events/default_cover.jpg',
                'type' => 'paid',
                'price' => 6000,
                'start_at' => '2026-11-27 09:30:00',
                'end_at' => '2026-11-27 17:00:00',
                'max_attendees' => 350,
            ],

            [
                'category' => 'Entertainment',
                'city' => 'Karachi',
                'name' => 'Comedy Night Karachi',
                'description' => 'A live comedy show featuring stand-up comedians and emerging performers from across Pakistan.',
                'location_name' => 'Arts Council of Pakistan',
                'address' => 'M.R. Kiyani Road, Karachi',
                'primary_image' => 'events/default_primary.jpg',
                'cover_image' => 'events/default_cover.jpg',
                'type' => 'paid',
                'price' => 1800,
                'start_at' => '2026-12-04 20:00:00',
                'end_at' => '2026-12-04 23:00:00',
                'max_attendees' => 500,
            ],

            [
                'category' => 'Conferences',
                'city' => 'Lahore',
                'name' => 'Pakistan Business & Innovation Conference',
                'description' => 'A conference focused on innovation, entrepreneurship, business transformation, and emerging market opportunities.',
                'location_name' => 'Pearl Continental Lahore',
                'primary_image' => 'events/default_primary.jpg',
                'cover_image' => 'events/default_cover.jpg',
                'address' => 'Mall Road, Lahore',
                'type' => 'paid',
                'price' => 5000,
                'start_at' => '2026-12-10 09:00:00',
                'end_at' => '2026-12-10 17:00:00',
                'max_attendees' => 400,
            ],

            [
                'category' => 'Festivals',
                'city' => 'Multan',
                'name' => 'Multan Cultural Heritage Festival',
                'description' => 'A cultural festival celebrating the heritage, crafts, music, food, and traditions of Southern Punjab.',
                'location_name' => 'Multan Arts Council',
                'address' => 'Gulgasht Colony, Multan',
                'primary_image' => 'events/default_primary.jpg',
                'cover_image' => 'events/default_cover.jpg',
                'type' => 'free',
                'price' => 0,
                'start_at' => '2026-12-18 15:00:00',
                'end_at' => '2026-12-20 22:00:00',
                'max_attendees' => 1000,
            ],

            [
                'category' => 'Workshops',
                'city' => 'Islamabad',
                'name' => 'Professional Photography Workshop',
                'description' => 'A hands-on photography workshop covering composition, lighting, camera settings, and practical shooting techniques.',
                'location_name' => 'Lok Virsa Heritage Museum',
                'address' => 'Garden Avenue, Shakarparian, Islamabad',
                'primary_image' => 'events/default_primary.jpg',
                'cover_image' => 'events/default_cover.jpg',
                'type' => 'paid',
                'price' => 2500,
                'start_at' => '2027-01-09 10:00:00',
                'end_at' => '2027-01-09 16:00:00',
                'max_attendees' => 40,
            ],

            [
                'category' => 'Exhibitions',
                'city' => 'Karachi',
                'name' => 'Karachi Technology Expo',
                'description' => 'A technology exhibition showcasing software products, IT services, startups, hardware, and digital solutions.',
                'location_name' => 'Expo Centre Karachi',
                'address' => 'University Road, Gulshan-e-Iqbal, Karachi',
                'primary_image' => 'events/default_primary.jpg',
                'cover_image' => 'events/default_cover.jpg',
                'type' => 'paid',
                'price' => 1000,
                'start_at' => '2027-01-15 10:00:00',
                'end_at' => '2027-01-17 19:00:00',
                'max_attendees' => 3000,
            ],

            [
                'category' => 'Community',
                'city' => 'Rawalpindi',
                'name' => 'Community Clean & Green Day',
                'description' => 'A community initiative encouraging residents to participate in neighborhood cleaning and tree plantation activities.',
                'location_name' => 'Ayub Park',
                'address' => 'Jhelum Road, Rawalpindi',
                'primary_image' => 'events/default_primary.jpg',
                'cover_image' => 'events/default_cover.jpg',
                'type' => 'free',
                'price' => 0,
                'start_at' => '2027-01-23 08:00:00',
                'end_at' => '2027-01-23 13:00:00',
                'max_attendees' => 300,
            ],

            [
                'category' => 'Seminars',
                'city' => 'Peshawar',
                'name' => 'Digital Business & Entrepreneurship Seminar',
                'description' => 'A seminar covering digital entrepreneurship, freelancing, online businesses, and opportunities in the digital economy.',
                'location_name' => 'Peshawar Services Club',
                'address' => 'Khyber Road, Peshawar',
                'primary_image' => 'events/default_primary.jpg',
                'cover_image' => 'events/default_cover.jpg',
                'type' => 'paid',
                'price' => 700,
                'start_at' => '2027-02-05 10:00:00',
                'end_at' => '2027-02-05 15:00:00',
                'max_attendees' => 250,
            ],
        ];

        foreach ($events as $event) {
            Event::create([
                'category_id' => Category::where('name', $event['category'])->firstOrFail()->id,
                'name' => $event['name'],
                'description' => $event['description'],
                'location_name' => $event['location_name'],
                'address' => $event['address'],
                'city_id' => City::where('name', $event['city'])->firstOrFail()->id,
                'primary_image' => $event['primary_image'],
                'cover_image' => $event['cover_image'],
                'map_url' => 'https://www.google.com/maps/place/Chichawatni,+Pakistan/@30.5410022,72.692501,11689m/data=!3m2!1e3!4b1!4m6!3m5!1s0x39232a0c466df715:0x9dbbc742bdf47fa!8m2!3d30.5372798!4d72.6983215!16zL20vMDgyZ2p2?entry=ttu&g_ep=EgoyMDI2MDgyNi4wIKXMDSoASAFQAw%3D%3D',
                'type' => $event['type'],
                'price' => $event['price'],
                'start_at' => $event['start_at'],
                'end_at' => $event['end_at'],
                'max_attendees' => $event['max_attendees'],
            ]);
        }
    }
}
